tienda_electronica/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using tienda_electronica.Data;
using tienda_electronica.Filters;
using tienda_electronica.Models.Usuarios;

namespace tienda_electronica.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ClienteData clienteData;
       
        public ClientesController (IConfiguration config)
        {
            clienteData = new ClienteData (config);
        }

        public IActionResult ModificarInformacion()
        {
            var idCliente = HttpContext.Session.GetInt32("idCliente");

            if (idCliente == null)
                return RedirectToAction("Login", "Cuenta");

            return View();
        }

        [AuthorizeRol("Administrador")]
        public IActionResult Gestion()
        {
            ViewBag.TituloMenu = "Gestion de Clientes";
            
            var clientes = clienteData.ObtenerClientes();
            return View(clientes);
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var clientes = clienteData.ObtenerClientePorId(id);
            if (clientes == null)
            {
                TempData["Error"] = "Cliente no encontrado.";
                return RedirectToAction("Gestion");
            }

            return View("Editar", clientes);
        }

        [HttpPost]
        public IActionResult Actualizar (Cliente cliente)
        {
            try
            {
                clienteData.EditarCliente(cliente);
                TempData["Mensaje Agregar"] = "Cliente editado correctamente.";

                return RedirectToAction("Gestion");
            }
            catch (Exception ex) 
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Editar");
            }
        }
    }
}

tienda_electronica/Controllers/FavoritosController.cs
using Microsoft.AspNetCore.Mvc;
using tienda_electronica.Data;

namespace tienda_electronica.Controllers
{
    public class FavoritosController : Controller
    {
        private readonly FavoritoData favoritoData;

        public FavoritosController (IConfiguration config)
        {
            favoritoData = new FavoritoData(config);
        }
        public IActionResult Index()
        {
            var idCliente = HttpContext.Session.GetInt32("idCliente");

            if (idCliente == null)
                return RedirectToAction("Login", "Cuenta");

            var favoritos = favoritoData.ObtenerFavoritosPorCliente(idCliente.Value);
            return View(favoritos);
        }

        [HttpPost]
        public IActionResult Agregar (int idProducto)
        {
            int? idCliente = HttpContext.Session.GetInt32("idCliente");
            if (idCliente == null)
                return RedirectToAction("Login", "Cuenta");

            favoritoData.AgregarFavorito(idCliente.Value, idProducto);
            return Redirect(Request.Headers["Referer"].ToString());
        }

        public IActionResult Eliminar(int id)
        {
            try
            {
                favoritoData.EliminarFavorito(id);
                TempData["Mensaje Eliminar"] = "Favorito eliminado correctamente.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

tienda_electronica/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using tienda_electronica.Data;
using tienda_electronica.Filters;
using tienda_electronica.Models.Usuarios;

namespace tienda_electronica.Controllers
{
    [AuthorizeRol("Administrador")]
    public class UsuariosController : Controller
    {
        private readonly UsuarioData usuarioData;

        public UsuariosController(IConfiguration config)
        {
            usuarioData = new UsuarioData(config);
        }
        public IActionResult Gestion()
        {
            ViewBag.TituloMenu = "Gestion de Usuarios";

            var usuarios = usuarioData.ObtenerUsuarios();
            return View(usuarios);
        }

        public IActionResult Eliminar(int id)
        {
            try
            {
                usuarioData.EliminarUsuarios(id);
                TempData["MensajeEliminar"] = "Usuario eliminado correctamente.";
                return RedirectToAction("Gestion");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Gestion");
            }
        }
        public IActionResult Agregar()
        {
            ViewBag.Roles = new List<SelectListItem>
            {
                new SelectListItem { Text = "Administrador", Value = "Administrador" },
                new SelectListItem { Text = "Gestor Productos", Value = "Gestor Productos" },
                new SelectListItem { Text = "Gestor Ventas", Value = "Gestor Ventas" }
            };
            
            return View(new Usuario());
        }

        [HttpPost]
        public IActionResult Guardar(Usuario usuario, IFormFile rutaFotoEmpleado)
        {
            try
            {
                if (usuario.idUsuario == 0)
                {
                    int idUsuario = usuarioData.AgregarUsuario(usuario, rutaFotoEmpleado);
                    TempData["MensajeAgregar"] = "Usuario agregado correctamente.";
                }
                else
                {
                    var usuarioExistente = usuarioData.ObtenerUsuarioPorId(usuario.idUsuario);

                    if (usuarioExistente == null)
                    {
                        TempData["Error"] = "No se encontró el usuario para editar.";
                        return RedirectToAction("Gestion");
                    }

                    if (rutaFotoEmpleado == null)
                    {
                        usuario.rutaFotoEmpleado = usuarioExistente.rutaFotoEmpleado;
                    }
                    usuarioData.EditarUsuario(usuario, rutaFotoEmpleado);
                    TempData["MensajeAgregar"] = "Usuario editado correctamente.";
                }

                return RedirectToAction("Gestion");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Agregar");
            }
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var usuario = usuarioData.ObtenerUsuarioPorId(id);

            if (usuario == null)
            {
                TempData["Error"] = "Usuario no encontrado";
                return RedirectToAction("Gestion");
            }

            ViewBag.Roles = new List<SelectListItem>
            {
                new SelectListItem { Text = "Administrador", Value = "Administrador" },
                new SelectListItem { Text = "Gestor Productos", Value = "Gestor Productos" },
                new SelectListItem { Text = "Gestor Ventas", Value = "Gestor Ventas" }
            };

            return View("Agregar", usuario);
        }
    }
}

tienda_electronica/Controllers/VentasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using tienda_electronica.Data;
using tienda_electronica.Filters;
using tienda_electronica.Models.Ventas;

namespace tienda_electronica.Controllers
{
    [AuthorizeRol("Administrador", "Gestor Ventas")]
    public class VentasController : Controller
    {
        private readonly VentaData ventaData;

        public VentasController (IConfiguration configuration)
        {
            ventaData = new VentaData (configuration);
        }
        public IActionResult Gestion()
        {
            ViewBag.TituloMenu = "Gestion de Ventas";
            
            var ventas = ventaData.ObtenerVentas();
            return View(ventas);
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var ventas = ventaData.ObtenerVentaPorId(id);

            if (ventas == null)
            {
                TempData["Error"] = "Venta no encontrada,";
                return RedirectToAction("Gestion");
            }

            ViewBag.Estados = new List<SelectListItem>
            {
                new SelectListItem { Text = "Pendiente", Value = "Pendiente" },
                new SelectListItem { Text = "Enviado", Value = "Enviado" },
                new SelectListItem { Text = "Entregado", Value = "Entregado" },
                new SelectListItem { Text = "Cancelado", Value = "Cancelado" },
            };

            return View(ventas);
        }

        [HttpPost]
        public IActionResult Actualizar(Venta venta)
        {
            try
            {
                ventaData.EditarVenta(venta);
                TempData["MensajeAgregar"] = "Venta editada correctamente.";

                return RedirectToAction("Gestion");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Editar");
            }
        }
    }
}

tienda_electronica/Views/Shared/_Layout.cshtml
@{
    var clienteLogueado = Context.Session.GetString("ClienteLogueado");
    bool estaLogueado = !string.IsNullOrEmpty(clienteLogueado);
}

<!DOCTYPE html>

<html lang="es">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/css/_LayoutStyles.css"/>

    @RenderSection("Estilos", required: false)
</head>
<body>
    <header class="header">
        <h1 class="logo">Hyper Mega Red</h1>
        <nav class="nav">
            <a href="@Url.Action("Index", "Home")" class="nav__link">Inicio</a>
            <a href="#" class="nav__link">Contacto</a>
            <a href="#" class="nav__link">Acerca de nosotros</a>
            @if (!estaLogueado)
            {
                <a href="@Url.Action("Login", "Cuenta")" class="nav__link">Iniciar Sesion</a>
            }
        </nav>
        <form class="input__container" method="get" action="@Url.Action("Index", "Productos")">
            <input class="input__search" type="text" name="busqueda" placeholder="¿Qué estás buscando?" value="@ViewBag.BusquedaActual" />
            <button type="submit" class="button__search">
                <img aria-hidden="true" class="input__lens" src="~/img/nav/lupa.png" />
            </button>
        </form>
        <div>
            @if (estaLogueado)
            {
                <a class="link__icon" href="@Url.Action("Index", "Favoritos")">
                    <img class="header__icon" src="~/img/nav/favorito.png" alt="Imagen de un corazon para agregar a favoritos" />
                </a>
                <a class="link__icon" href="@Url.Action("Index", "Carritos")">
                    <img class="header__icon" src="~/img/nav/carro-de-la-compra.png" alt="Imagen de un carrito de compras para agregar productos" />
                </a>
                <a class="link__icon" href="@Url.Action("ModificarInformacion", "Clientes")">
                    <img class="header__icon" src="~/img/nav/usuario.png" alt="Imagen de un perfil para revisar el perfil del usuario" />
                </a>
            }
        </div>
    </header>

    <div>
        @RenderBody()
    </div>

    <footer class="footer">

        <div class="footer__container">
            <div class="footer__field">
                <h1 class="logo title__footer">Hyper Mega Red</h1>
                <p class="store__information footer__elements--spacing">
                    Somos la mejor plataforma de venta de productos electronicos de Bolivia. Confia en nosotros
                    para sus pedidos y compras en linea de los ultimos productos electronicos.
                </p>
            </div>

            <div class="footer__field">
                <h2 class="subtitle__footer">Soporte</h2>
                <p class="store__information footer__elements--spacing">Cochabamba-Bolivia Zona Chimba Av. Ingavi calle Heredia nro 4467</p>
            </div>

            <div class="footer__field">
                <h2 class="subtitle__footer"r>Contactanos</h2>
                <span class="footer__elements--spacing">hypermegaredsoporte@gmail.com</span>
                <span class="footer__elements--spacing">+591 77912729</span>
                <div class="footer__elements--spacing">
                    <a>
                        <img class="footer__socialmedia" src="~/img/footer/icons8-facebook-24.png" alt="Icono de facebook de la tienda electronica" />
                    </a>
                    <a>
                        <img class="footer__socialmedia" src="~/img/footer/icons8-instagram-24.png" alt="Icono de instagram de la tienda electronica" />
                    </a>
                    <a>
                        <img class="footer__socialmedia" src="~/img/footer/icons8-twitter-24.png" alt="Icono de twiter de la tienda electronica" />
                    </a>
                    <a>
                        <img class="footer__socialmedia" src="~/img/footer/icons8-linkedin-24.png" alt="Icono de linkedin de la tienda electronica" />
                    </a>
                </div>
            </div>
        </div>

        <span class="footer__copyright">Copyright 2025. All right reserved</span>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

tienda_electronica/Views/Shared/_LayoutAdmin.cshtml
@{
    var rolUsuario = Context.Session.GetString("RolUsuario");
    var nombreUsuario = Context.Session.GetString("NombreUsuario");
    var apellidoUsuario = Context.Session.GetString("ApellidoUsuario");
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Panel de Gestion</title>

    <link href="~/css/admin.css" rel="stylesheet" />

    @RenderSection("Estilos", required: false)
</head>
<body>

    <div class="menu">
        <div class="menu__container">

            <div class="menu__logo">
                <a>
                    <span class="menu__name">Hyper Mega Red</span>
                </a>
            </div>

            <nav class="nav">
                <ul class="nav__list">
                    @if (rolUsuario == "Administrador" || rolUsuario == "Gestor Productos")
                    {
                        <li class="nav__item">
                            <a href="@Url.Action("Gestion", "Productos")" class="nav__link">
                                <img class="menu__img" src="~/img/layoutadmin/productos.png" />
                                <span>Productos</span>
                            </a>
                        </li>
                        <li class="nav__item">
                            <a href="@Url.Action("Gestion", "Categorias")" class="nav__link">
                                <img class="menu__img" src="~/img/layoutadmin/categorias.png" />
                                <span>Categorias</span>
                            </a>
                        </li>
                    }

                    @if (rolUsuario == "Administrador")
                    {
                        <li class="nav__item">
                            <a href="@Url.Action("Gestion", "Usuarios")" class="nav__link">
                                <img class="menu__img" src="~/img/layoutadmin/usuarios.png" />
                                <span>Usuarios</span>
                            </a>
                        </li>
                        <li class="nav__item">
                            <a href="@Url.Action("Gestion", "Clientes")" class="nav__link">
                                <img class="menu__img" src="~/img/layoutadmin/usuarios.png" />
                                <span>Clientes</span>
                            </a>
                        </li>
                    }

                    @if (rolUsuario == "Administrador" || rolUsuario == "Gestor Ventas")
                    {
                        <li class="nav__item">
                            <a href="@Url.Action("Gestion", "Ventas")" class="nav__link">
                                <img class="menu__img" src="~/img/layoutadmin/ventas.png" />
                                <span>Ventas</span>
                            </a>
                        </li>
                    }
                </ul>
            </nav>

            <div class="menu__signout">
                <form method="post" action="@Url.Action("Logout", "Cuenta")">
                    <button class="btn__signout" type="submit">
                        <img class="menu__img" src="~/img/layoutadmin/logout.png" />
                        Cerrar Sesion
                    </button>
                </form>
            </div>
        </div>
    </div>

    <header class="header">
        <div class="header__container">

            <div>
                @if(ViewBag.TituloMenu != null)
                {
                    <span class="header__container--title">@ViewBag.TituloMenu</span>
                }
                <div class="header__fullname">
                    <span class="header__name">@nombreUsuario</span>
                    <span class="header__lastname">@apellidoUsuario</span>
                </div>
            </div>

        </div>
    </header>

    <div class="main">
        @RenderBody()
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>