tienda_electronica/Controllers/FavoritosController.cs
using Microsoft.AspNetCore.Mvc;
using tienda_electronica.Data;

namespace tienda_electronica.Controllers
{
    public class FavoritosController : Controller
    {
        private readonly FavoritoData favoritoData;

        public FavoritosController (IConfiguration config)
        {
            favoritoData = new FavoritoData(config);
        }
        public IActionResult Index()
        {
            var idCliente = HttpContext.Session.GetInt32("idCliente");

            if (idCliente == null)
                return RedirectToAction("Login", "Cuenta");

            var favoritos = favoritoData.ObtenerFavoritosPorCliente(idCliente.Value);
            return View(favoritos);
        }

        [HttpPost]
        public IActionResult Agregar (int idProducto)
        {
            int? idCliente = HttpContext.Session.GetInt32("idCliente");
            if (idCliente == null)
                return RedirectToAction("Login", "Cuenta");

            favoritoData.AgregarFavorito(idCliente.Value, idProducto);
            return Redirect(Request.Headers["Referer"].ToString());
        }

        public IActionResult Eliminar(int id)
        {
            try
            {
                favoritoData.EliminarFavorito(id);
                TempData["Mensaje Eliminar"] = "Favorito eliminado correctamente.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

tienda_electronica/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tienda_electronica.Data;
using tienda_electronica.Models;

namespace tienda_electronica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ProductoData productoData;
        private readonly CategoriaData categoriaData;
        private readonly FavoritoData favoritoData;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            productoData = new ProductoData(configuration);
            categoriaData = new CategoriaData(configuration);
            favoritoData = new FavoritoData(configuration);
        }

        public IActionResult Index()
        {
            var productos = productoData.ObtenerProductos();
            var categorias = categoriaData.ObtenerCategorias();
            ViewBag.Categorias = categorias;

            var idCliente = HttpContext.Session.GetInt32("idCliente");
            var favoritosIds = new List<int>();
            if (idCliente != null)
            {
                var favoritos = favoritoData.ObtenerFavoritosPorCliente(idCliente.Value);
                favoritosIds = favoritos.Select(f => f.idProducto).ToList();
            }

            ViewBag.FavoritosIds = favoritosIds;

            return View(productos);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tienda_electronica/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using tienda_electronica.Data;
using tienda_electronica.Filters;
using tienda_electronica.Models;
using tienda_electronica.Models.Categorias;
using tienda_electronica.Models.Productos;

namespace tienda_electronica.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ProductoData productoData;
        private readonly CategoriaData categoriaData;
        private readonly FavoritoData favoritoData;

        public ProductosController(IConfiguration config)
        {
            productoData = new ProductoData(config);
            categoriaData = new CategoriaData(config);
            favoritoData = new FavoritoData(config);
        }
        public IActionResult Index(int? categoriaId, string busqueda)
        {
            List<Producto> productos;

            if (categoriaId.HasValue)
            {
                productos = productoData.ObtenerPorCategoria(categoriaId.Value);
            }
            else
            {
                productos = productoData.ObtenerProductos();
            }

            if (!string.IsNullOrEmpty(busqueda))
            {
                productos = productos
                    .Where(p => p.nombre.Contains(busqueda, StringComparison.OrdinalIgnoreCase) || 
                            p.descripcion.Contains(busqueda, StringComparison.OrdinalIgnoreCase))
                    .ToList();      
            }

            var categorias = categoriaData.ObtenerCategorias();
            ViewBag.Categorias = categorias;
            ViewBag.CategoriaSeleccionadaId = categoriaId;
            ViewBag.BusquedaActual = busqueda;

            var idCliente = HttpContext.Session.GetInt32("idCliente");
            var favoritosIds = new List<int>();
            if (idCliente != null)
            {
                var favoritos = favoritoData.ObtenerFavoritosPorCliente(idCliente.Value);
                favoritosIds = favoritos.Select(f => f.idProducto).ToList();
            }

            ViewBag.FavoritosIds = favoritosIds;


            return View(productos);
        }
        public IActionResult Detalle(int id)
        {
            var producto = productoData.ObtenerProductoPorId(id);
            if (producto == null) 
            {
                return NotFound();
            }
            //ViewBag.ProductoId = id;
            return View(producto);
        }

        [AuthorizeRol("Administrador", "Gestor Productos")]
        public IActionResult Gestion()
        {
            ViewBag.TituloMenu = "Gestion de Productos";

            var productos = productoData.ObtenerProductos();
            return View(productos);
        }

        public IActionResult Eliminar(int id)
        {
            try
            {
                if (productoData.ProductoTienePedidos(id))
                {
                    TempData["Error"] = "No se puede eliminar el producto porque está relacionado con pedidos.";
                    return RedirectToAction("Gestion"); 
                }
                else
                {
                    productoData.EliminarProducto(id);
                    TempData["MensajeEliminar"] = "Producto eliminado correctamente.";
                    return RedirectToAction("Gestion");
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Gestion");
            }
        }

        public IActionResult Agregar() 
        {
            var categorias = categoriaData.ObtenerCategorias();
            ViewBag.Categorias = categorias;
            return View(new Producto());
        }

        [HttpPost]
        public IActionResult Guardar(Producto producto, IFormFile imagenPrincipal, List<IFormFile> imagenesAdicionales)
        {
            try
            {
                if (producto.idProducto == 0)
                {
                    int idProducto = productoData.AgregarProducto(producto, imagenPrincipal, imagenesAdicionales);
                    TempData["MensajeAgregar"] = "Producto agregado correctamente.";
                }
                else
                {
                    productoData.EditarProducto(producto, imagenPrincipal, imagenesAdicionales);
                    TempData["MensajeAgregar"] = "Producto editado correctamente.";
                }

                return RedirectToAction("Gestion");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Agregar");
            }
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var producto = productoData.ObtenerProductoPorId(id);
            if (producto == null)
            {
                TempData["Error"] = "Producto no encontrado";
                return RedirectToAction("Gestion");
            }

            var categorias = categoriaData.ObtenerCategorias();
            ViewBag.Categorias = categorias;

            return View("Agregar", producto);
        }

    }
}

tienda_electronica/Views/Home/Index.cshtml
@model List<tienda_electronica.Models.Productos.Producto> 

@{
    ViewData["Title"] = "Pagina de Inicio";
    Layout = "_Layout";
    List<int> favoritosIds = ViewBag.FavoritosIds ?? new List<int>();
}

@section Estilos {
<link rel="stylesheet" href="~/css/inicio.css" />
}

<main class="content">
    <div class="promotions__container">
        <ul>
            <li>
                <a href="#">
                    <img class="promotions__apple" src="~/img/home/appledescuento.jpg" alt="Imagen de descuentos del 10% de productos apple" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img class="promotions__samsung" src="~/img/home/descuentorelojes.jpg" alt="Imagen de descuentos del 25% de relojes de samsung" />
                </a>
            </li>
        </ul>
    </div>

    <section class="section__products">
        <div class="section__containertitle">
            <div class="barra"></div>
            <div class="title__container">
                <h4 class="section__title">Productos</h4>
            </div>
            <div class="section__arrow">
                <button class="button__arrow">
                    <img class="arrow_img" src="~/img/home/flecha-izquierda.png" />
                </button>
                <button class="button__arrow">

                    <img class="arrow_img" src="~/img/home/flecha-derecha.png" />
                </button>
            </div>
        </div>
        <div class="article__container">
            @foreach (var producto in Model)
            {
                <article class="product__container">
                    <div class="img__container">
                        <img class="img__product" src="@producto.rutaImagen" />
                        <form asp-controller="Favoritos" asp-action="Agregar" method="post">
                            <input type="hidden" name="idProducto" value="@producto.idProducto" />
                            <button type="submit" class="button__favorite">
                                <img class="icon__product" src="~/img/nav/@(favoritosIds.Contains(producto.idProducto) ? "favorito-lleno.png" : "favorito.png")" />
                            </button>
                        </form>
                        <a href="@Url.Action("Detalle", "Productos" , new { id = producto.idProducto } )" class="button__eye">
                            <img class="icon__product" src="~/img/home/productos/ojo-abierto.png" />
                        </a>
                    </div>
                    <header class="product__header">
                        <h3 class="product__name">@producto.nombre</h3>
                        <div class="container__price">
                            <span>@producto.precio</span>
                            @if (producto.precioDescuento > 0)
                            {
                                <span class="discount__price">@producto.precioDescuento</span>
                            }
                        </div>
                    </header>
                </article>
            }
        </div>
        <div class="view__container">
            <a href="@Url.Action("Index", "Productos")" class="bottom__view">Ver todos los productos</a>
        </div>
        <hr class="section__divider"/>
    </section>

    <section>
        <div class="section__containertitle">
            <div class="barra"></div>
            <div class="title__container">
                <h4 class="section__title">Categorias</h4>
            </div>
            <div class="section__arrow">
                <button class="button__arrow">
                    <img class="arrow_img" src="~/img/home/flecha-izquierda.png" />
                </button>
                <button class="button__arrow">

                    <img class="arrow_img" src="~/img/home/flecha-derecha.png" />
                </button>
            </div>
        </div>
        <div class="article__container">
            @foreach (var categoria in ViewBag.Categorias)
            {
                <article class="article__container">
                    <div class="category__container">
                        <a class="category__content" href="@Url.Action("Index", "Productos", new { categoriaId = categoria.idCategoria })">
                            <img class="img__category" src="~/img/home/categorias/telefono-inteligente.png" />
                            <h3 class="name__category">@categoria.nombre</h3>
                        </a>
                    </div>
                </article>
            }
        </div>
        <hr class="section__divider" />
    </section>
    <section>
        <img class="img__speaker" src="~/img/home/publicidadparlantes.jpg" />
    </section>
    <section class="benefits__container">
        <div class="benefits__content">
            <div class="benefits__center">
                <div class="benefits__img--background">
                    <img class="benefits__img" src="~/img/home/servicios/camion.jpg" />
                </div>
            </div>
            <span class="benefits__title">ENTREGA GRATUITA Y RAPIDA</span>
            <p class="benefits__info">Envio gratuito para todos los pedidos superiores a 300 Bs</p>
        </div>

        <div class="benefits__content">
            <div class="benefits__center">
                <div class="benefits__img--background">
                    <img class="benefits__img" src="~/img/home/servicios/audifonos.jpg" />
                </div>
            </div>
            <span class="benefits__title">SERVICIO AL CLIENTE 24/7</span>
            <p class="benefits__info">Amigable atencion al cliente 24/7</p>
        </div>

        <div class="benefits__content">
            <div class="benefits__center">
                <div class="benefits__img--background">
                    <img class="benefits__img" src="~/img/home/servicios/correcto.jpg" />
                </div>
            </div>
            <span class="benefits__title">GARANTIA DE DEVOLUCION DE DINERO</span>
            <p class="benefits__info">Devolvemos el dinero en 30 dias</p>
        </div>
    </section>
</main>

@section Scripts {
    <script>
                document.addEventListener('DOMContentLoaded', function() {
            const productContainer = document.querySelector('.article__container');
            const leftArrow = document.querySelector('.button__arrow:first-child');
            const rightArrow = document.querySelector('.button__arrow:last-child');

            // Cantidad de píxeles a desplazar (ajusta según tu diseño)
            const scrollAmount = 300;

            // Flecha izquierda (desplaza hacia atrás)
            leftArrow.addEventListener('click', function() {
                productContainer.scrollBy({
                    left: -scrollAmount,
                    behavior: 'smooth'
                });
            });

            // Flecha derecha (desplaza hacia adelante)
            rightArrow.addEventListener('click', function() {
                productContainer.scrollBy({
                    left: scrollAmount,
                    behavior: 'smooth'
                });
            });

            // Opcional: Mostrar/ocultar flechas según posición del scroll
            function updateArrowVisibility() {
                leftArrow.style.visibility = productContainer.scrollLeft > 0 ? 'visible' : 'hidden';
                rightArrow.style.visibility = productContainer.scrollLeft <
                    (productContainer.scrollWidth - productContainer.clientWidth) ? 'visible' : 'hidden';
            }

            productContainer.addEventListener('scroll', updateArrowVisibility);
            updateArrowVisibility(); // Ejecutar al cargar la página
        });
    </script>
}